DECLARE
  LAST_YM_VAR INTEGER:=0;
BEGIN
  YM:=DWSEAI01.YMM2YM({YMM});
  SELECT MAX(CAST(SUBSTR(PARTITION_NAME, -6) AS INTEGER))
  INTO LAST_YM_VAR
  FROM ALL_TAB_PARTITIONS
  WHERE TABLE_OWNER='DWSEAI01'
  AND TABLE_NAME   ='{TARGET_TABLE}';
  IF YM   >LAST_YM_VAR THEN
    EXECUTE IMMEDIATE
    'ALTER TABLE DWSEAI01.{TARGET_TABLE} ADD PARTITION {PART_NM_TEMPL}_'||YM||' VALUES ('||YM||')   
LOGGING   
TABLESPACE DWREAI01   
PCTFREE 0   
INITRANS 1   
STORAGE   
(     
BUFFER_POOL DEFAULT   
)   
COMPRESS FOR QUERY HIGH   
(    
SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_3 VALUES
(  
''AUSTRALIA'', ''NEW ZEALAND''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_4 VALUES
(  
''IRELAND'', ''UK''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_6 VALUES
(  
''GERMANY'', ''FRANCE''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_9 VALUES
(  
''BELGIUM'', ''NETHERLANDS''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_11 VALUES
(  
''SWITZERLAND''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_14 VALUES
(  
''TURKEY'', ''UKRAINE'', ''ROMANIA'', ''LATVIA'', ''POLAND'', ''ESTONIA'', ''HUNGARY'', ''CZECH REPUBLIC'', ''SLOVAKIA'', ''LITHUANIA'', ''SLOVENIA'', ''BULGARIA'', ''CROATIA''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_15 VALUES
(  
''ITALY''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_20 VALUES
(  
''AUSTRIA''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_24 VALUES
(  
''PORTUGAL'', ''SPAIN''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_33 VALUES
(  
''RUSSIA'', ''KAZAKHSTAN''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_34 VALUES
(  
''INDIA''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_36 VALUES
(  
''NORWAY'', ''DENMARK'', ''SWEDEN'', ''FINLAND''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_37 VALUES
(  
''GREECE''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_39 VALUES
(  
''SOUTH AFRICA'', ''BOTSWANA'', ''NAMIBIA''
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH , SUBPARTITION {PART_NM_TEMPL}_'||YM||'_AFF_OTHR VALUES
(  
DEFAULT
)
TABLESPACE DWRGDW01_ORDERS COMPRESS FOR QUERY HIGH    
)'
    ;
  END IF;
END;
