CREATE MATERIALIZED VIEW "DWSEAI01"."OMS_MV"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWREAI01" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWREAI01" 
  REFRESH FAST ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS ENABLE QUERY REWRITE
  AS SELECT COUNT(IMC_KEY_NO) AS IMC_KEY_NO_CNT,
    YEARMONTH,
     CASE CAST(APPL_DT/100 AS INTEGER) WHEN YEARMONTH THEN 1 ELSE 0 END AS NEW_APP_FLAG,
         CASE
      WHEN floor(APPL_DT/100) = YEARMONTH
      THEN '1 Month of Membership'
      WHEN MONTHS_BETWEEN(to_date(YEARMONTH*100+1,'yyyymmdd'),to_date(floor(APPL_DT/100)*100+1,'yyyymmdd')) <=12
      THEN '2 to 12 Months of Membership'
      WHEN MONTHS_BETWEEN(to_date(YEARMONTH*100+1,'yyyymmdd'),to_date(floor(APPL_DT/100)*100+1,'yyyymmdd')) >12
      THEN '13+ Months of Membership'
END AS TENURE,
    U35_FLAG,
    COUNTRY,
    GL_SEGMENT,
    SALES_REGION,
    STATE,
    IMC_TYPE,
    DIST_TYPE,
    RCNCY_CNT,
    FRQNCY_CNT,
    SUM(BV_USD)                      AS BV_USD,
    SUM(BV_USD_EOM)                  AS BV_USD_EOM,
    SUM(PV)                          AS PV,
    SUM(PV_EOM)                      AS PV_EOM,
    SUM(OMS_UNIT_CNT)                AS OMS_UNIT_CNT,
    SUM(BUYER_FLAG)                  AS BUYERS_CNT,
    SUM(SPONSORED_ABOS_CNT)          AS SPONSORED_ABOS_CNT,
    SUM(SPONSORED_RCS_CNT)           AS SPONSORED_RCS_CNT,
    SUM(ABOS_SPONSORING_ABOS_FLAG)   AS ABOS_SPONSORING_ABOS_FLAG,
    SUM(ABOS_SPONSORING_RCS_FLAG)    AS ABOS_SPONSORING_RCS_FLAG,
    SUM(ABOS_SPONSORING_IMCS_FLAG)   AS ABOS_SPONSORING_IMCS_FLAG,
    SUM(HIGH_IMC)                    AS HIGH_IMC,
    SUM(HIGH_VOLUME)                 AS HIGH_VOLUME,
    SUM(HIGH_BV)                     AS HIGH_BV,
    SUM(R_IMC)                       AS R_IMC,
    COUNT(BV_USD)                    AS BV_USD_CNT,
    COUNT(BV_USD_EOM)                AS BV_USD_EOM_CNT,
    COUNT(PV)                        AS PV_CNT,
    COUNT(PV_EOM)                    AS PV_EOM_CNT,
    COUNT(OMS_UNIT_CNT)              AS OMS_UNIT_CNT_CNT,
    COUNT(BUYER_FLAG)                AS BUYERS_CNT_CNT,
    COUNT(SPONSORED_ABOS_CNT)        AS SPONSORED_ABOS_CNT_CNT,
    COUNT(SPONSORED_RCS_CNT)         AS SPONSORED_RCS_CNT_CNT,
    COUNT(ABOS_SPONSORING_ABOS_FLAG) AS ABOS_SPONSORING_ABOS_FLAG_CNT,
    COUNT(ABOS_SPONSORING_RCS_FLAG)  AS ABOS_SPONSORING_RCS_FLAG_CNT,
    COUNT(ABOS_SPONSORING_IMCS_FLAG) AS ABOS_SPONSORING_IMCS_FLAG_CNT,
    COUNT(HIGH_IMC)                  AS HIGH_IMC_CNT,
    COUNT(HIGH_VOLUME)               AS HIGH_VOLUME_CNT,
    COUNT(HIGH_BV)                   AS HIGH_BV_CNT,
    COUNT(R_IMC)                     AS R_IMC_CNT,
    COUNT(*)                         AS CNT
  FROM DWSEAI01.OMS_TEMP_RMS_PART
  GROUP BY YEARMONTH,
    U35_FLAG,
    COUNTRY,
    GL_SEGMENT,
    SALES_REGION,
    STATE,
    IMC_TYPE,
    DIST_TYPE,
    RCNCY_CNT,
    FRQNCY_CNT,
     CASE CAST(APPL_DT/100 AS INTEGER) WHEN YEARMONTH THEN 1 ELSE 0 END,
         CASE
      WHEN floor(APPL_DT/100) = YEARMONTH
      THEN '1 Month of Membership'
      WHEN MONTHS_BETWEEN(to_date(YEARMONTH*100+1,'yyyymmdd'),to_date(floor(APPL_DT/100)*100+1,'yyyymmdd')) <=12
      THEN '2 to 12 Months of Membership'
      WHEN MONTHS_BETWEEN(to_date(YEARMONTH*100+1,'yyyymmdd'),to_date(floor(APPL_DT/100)*100+1,'yyyymmdd')) >12
      THEN '13+ Months of Membership'
END
